In [1]:
# Your objective is to analyze the data to show how four treatments (Capomulin, Infubinol, Ketapril, and Placebo) compare
#Creating a scatter plot that shows how the tumor volume changes over time for each treatment.
#Creating a scatter plot that shows how the number of metastatic (cancer spreading) sites changes over time for each treatment.
#Creating a scatter plot that shows the number of mice still alive through the course of treatment (Survival Rate)
#Creating a bar graph that compares the total % tumor volume change for each drug across the full 45 days.

In [2]:
%matplotlib notebook

In [3]:
#Import libraries
import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt
import seaborn as sb

In [4]:
data_csv = "Resources/clinicaltrial_data.csv"
mouse_csv = "Resources/mouse_drug_data.csv"

In [5]:
data_df = pd.read_csv(data_csv)
mouse_df = pd.read_csv(mouse_csv)

In [6]:
#verifying data was read in correctly
data_df.head()

  Mouse ID  Timepoint  Tumor Volume (mm3)  Metastatic Sites
0     b128          0                45.0                 0
1     f932          0                45.0                 0
2     g107          0                45.0                 0
3     a457          0                45.0                 0
4     c819          0                45.0                 0

In [7]:
#verifying data was read in correctly
mouse_df.head()

  Mouse ID      Drug
0     f234  Stelasyn
1     x402  Stelasyn
2     a492  Stelasyn
3     w540  Stelasyn
4     v764  Stelasyn

In [8]:
# make one big table & check to see if there are errors
bigtable_df = pd.merge(data_df, mouse_df, on='Mouse ID')

#count how many 
bigtable_df['Drug'].value_counts()

Capomulin    230
Ramicane     228
Stelasyn     194
Ketapril     188
Naftisol     186
Zoniferol    182
Placebo      181
Ceftamin     178
Infubinol    178
Propriva     161
Name: Drug, dtype: int64

In [14]:
new_bigtable_df = bigtable_df.set_index("Drug")
new_bigtable_df.head(20)

          Mouse ID  Timepoint  Tumor Volume (mm3)  Metastatic Sites
Drug
Capomulin     b128          0           45.000000                 0
Capomulin     b128          5           45.651331                 0
Capomulin     b128         10           43.270852                 0
Capomulin     b128         15           43.784893                 0
Capomulin     b128         20           42.731552                 0
Capomulin     b128         25           43.262145                 1
Capomulin     b128         30           40.605335                 1
Capomulin     b128         35           37.967644                 1
Capomulin     b128         40           38.379726                 2
Capomulin     b128         45           38.982878                 2
Ketapril      f932          0           45.000000                 0
Ketapril      g107          0           45.000000                 0
Ketapril      g107          5           48.791665                 0
Ketapril      g107         10           53.435987                 0
Ketapril      g107         15           58.135545                 0
Ketapril      g107         20           62.706031                 0
Ketapril      g107         25           64.663626                 0
Ketapril      g107         30           69.160520                 0
Ketapril      g107         35           71.905117                 0
Ketapril      a457          0           45.000000                 0

In [29]:
Capomulin_df = new_bigtable_df.loc['Capomulin',['Mouse ID', 'Timepoint', 'Tumor Volume (mm3)']]
#if mouseID(n) == mouseID(n+1), then tumorchange(n) = tumorvolume(n+1)-tumorvolumen(n) and
#timediff(n) = timepoint(n+1) - timepoint(n)
#Capomulin_df['Time Change'] = np.where(Capomulin_df['Mouse ID'] == Capomulin_df['Mouse ID'].shift(1),
#                                       (Capomulin_df['Timepoint'] - Capomulin_df['Timepoint'].shift(1)), 0)
#Capomulin_df['Volume Change'] = np.where(Capomulin_df['Mouse ID'] == Capomulin_df['Mouse ID'].shift(1),
#                                       (Capomulin_df['Tumor Volume (mm3)'] - Capomulin_df['Tumor Volume (mm3)'].shift(1)), 0)
for index in Capomulin_df.index:
    if Capomulin
Capomulin_df.head(25)

          Mouse ID  Timepoint  Tumor Volume (mm3)  Time Change  Volume Change
Drug
Capomulin     b128          0           45.000000          0.0       0.000000
Capomulin     b128          5           45.651331          5.0       0.651331
Capomulin     b128         10           43.270852          5.0      -2.380479
Capomulin     b128         15           43.784893          5.0       0.514042
Capomulin     b128         20           42.731552          5.0      -1.053341
Capomulin     b128         25           43.262145          5.0       0.530593
Capomulin     b128         30           40.605335          5.0      -2.656810
Capomulin     b128         35           37.967644          5.0      -2.637690
Capomulin     b128         40           38.379726          5.0       0.412082
Capomulin     b128         45           38.982878          5.0       0.603152
Capomulin     j246          0           45.000000          0.0       0.000000
Capomulin     j246          5           45.641438          5.0       0.641438
Capomulin     j246         10           46.408361          5.0       0.766923
Capomulin     j246         15           43.312654          5.0      -3.095707
Capomulin     j246         20           44.020370          5.0       0.707716
Capomulin     j246         25           44.555226          5.0       0.534856
Capomulin     j246         30           38.044082          5.0      -6.511144
Capomulin     j246         35           38.753265          5.0       0.709183
Capomulin     r554          0           45.000000          0.0       0.000000
Capomulin     r554          5           45.781746          5.0       0.781746
Capomulin     r554         10           39.005493          5.0      -6.776252
Capomulin     r554         15           35.463758          5.0      -3.541736
Capomulin     r554         20           36.015589          5.0       0.551831
Capomulin     r554         25           33.893345          5.0      -2.122243
Capomulin     r554         30           32.680655          5.0      -1.212691

In [ ]:
#Creating a scatter plot that shows how the tumor volume changes over time for each treatment.