In [1]:
# Your objective is to analyze the data to show how four treatments (Capomulin, Infubinol, Ketapril, and Placebo) compare
#Creating a scatter plot that shows how the tumor volume changes over time for each treatment.
#Creating a scatter plot that shows how the number of metastatic (cancer spreading) sites changes over time for each treatment.
#Creating a scatter plot that shows the number of mice still alive through the course of treatment (Survival Rate)
#Creating a bar graph that compares the total % tumor volume change for each drug across the full 45 days.

In [2]:
%matplotlib notebook

In [3]:
#Import libraries
import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt
import seaborn as sb

In [4]:
data_csv = "Resources/clinicaltrial_data.csv"
mouse_csv = "Resources/mouse_drug_data.csv"

In [5]:
data_df = pd.read_csv(data_csv)
mouse_df = pd.read_csv(mouse_csv)

In [49]:
#verifying data was read in correctly
data_df.head()

  Mouse ID  Timepoint  Tumor Volume (mm3)  Metastatic Sites
0     b128          0                45.0                 0
1     f932          0                45.0                 0
2     g107          0                45.0                 0
3     a457          0                45.0                 0
4     c819          0                45.0                 0

In [7]:
#verifying data was read in correctly
mouse_df.head()

  Mouse ID      Drug
0     f234  Stelasyn
1     x402  Stelasyn
2     a492  Stelasyn
3     w540  Stelasyn
4     v764  Stelasyn

In [8]:
# make one big table & check to see if there are errors
bigtable_df = pd.merge(data_df, mouse_df, on='Mouse ID')

#count how many 
bigtable_df['Drug'].value_counts()

Capomulin    230
Ramicane     228
Stelasyn     194
Ketapril     188
Naftisol     186
Zoniferol    182
Placebo      181
Infubinol    178
Ceftamin     178
Propriva     161
Name: Drug, dtype: int64

In [9]:
new_bigtable_df = bigtable_df.set_index("Drug")
new_bigtable_df.head()

          Mouse ID  Timepoint  Tumor Volume (mm3)  Metastatic Sites
Drug
Capomulin     b128          0           45.000000                 0
Capomulin     b128          5           45.651331                 0
Capomulin     b128         10           43.270852                 0
Capomulin     b128         15           43.784893                 0
Capomulin     b128         20           42.731552                 0

In [154]:
Capomulin_df = new_bigtable_df.loc['Capomulin',['Mouse ID', 'Timepoint', 'Tumor Volume (mm3)']]

#reset index
#Capomulin_df = Capomulin_df.reset_index()

Mouse_ID = Capomulin_df['Mouse ID']
Mouse_ID = Mouse_ID.value_counts()
Mouse_ID_df = pd.DataFrame(Mouse_ID)
Mouse_ID_df = Mouse_ID_df.reset_index()
Mouse_ID_df = Mouse_ID_df.rename(index=str, columns={ "Mouse ID": "Count"})
Mouse_ID_df['max'] = 0.0

for i, row in Mouse_ID_df.iterrows():
    value = Capomulin_df.loc[Capomulin_df['Mouse ID'] == Mouse_ID_df['index'][i], 'Tumor Volume (mm3)'].max()
    Mouse_ID_df.at[i,'max'] = value

          Mouse ID  Timepoint  Tumor Volume (mm3)
Drug
Capomulin     b128          0           45.000000
Capomulin     b128          5           45.651331
Capomulin     b128         10           43.270852
Capomulin     b128         15           43.784893
Capomulin     b128         20           42.731552
Capomulin     b128         25           43.262145
Capomulin     b128         30           40.605335
Capomulin     b128         35           37.967644
Capomulin     b128         40           38.379726
Capomulin     b128         45           38.982878
Capomulin     j246          0           45.000000
Capomulin     j246          5           45.641438
Capomulin     j246         10           46.408361
Capomulin     j246         15           43.312654
Capomulin     j246         20           44.020370
Capomulin     j246         25           44.555226
Capomulin     j246         30           38.044082
Capomulin     j246         35           38.753265
Capomulin     r554          0           45.000000
Capomulin     r554          5           45.781746
Capomulin     r554         10           39.005493
Capomulin     r554         15           35.463758
Capomulin     r554         20           36.015589
Capomulin     r554         25           33.893345
Capomulin     r554         30           32.680655
Capomulin     r554         35           33.069337
Capomulin     r554         40           31.804841
Capomulin     r554         45           32.377357
Capomulin     s185          0           45.000000
Capomulin     s185          5           43.878496
...            ...        ...                 ...
Capomulin     i557         25           44.596219
Capomulin     i557         30           45.261384
Capomulin     i557         35           45.941949
Capomulin     i557         40           46.821070
Capomulin     i557         45           47.685963
Capomulin     m957          0           45.000000
Capomulin     m957          5           45.622381
Capomulin     m957         10           46.414518
Capomulin     m957         15           39.804453
Capomulin     m957         20           38.909349
Capomulin     m957         25           37.695432
Capomulin     m957         30           38.212479
Capomulin     m957         35           32.562839
Capomulin     m957         40           32.947615
Capomulin     m957         45           33.329098
Capomulin     f966          0           45.000000
Capomulin     f966          5           38.796474
Capomulin     f966         10           35.624403
Capomulin     f966         15           32.623003
Capomulin     f966         20           30.485985
Capomulin     m601          0           45.000000
Capomulin     m601          5           41.408591
Capomulin     m601         10           36.825367
Capomulin     m601         15           35.464612
Capomulin     m601         20           34.255732
Capomulin     m601         25           33.118756
Capomulin     m601         30           31.758275
Capomulin     m601         35           30.834357
Capomulin     m601         40           31.378045
Capomulin     m601         45           28.430964

[230 rows x 3 columns]

In [34]:
#Creating a scatter plot that shows how the tumor volume changes over time for each treatment.